version: "3.7"

services:

    sql-database:
        ports:
            # Accès au serveur MySQL
            - "3369:3306"

    webappserver:
        ports:
            # Accès à l'interface web
            - "6969:80"
        volumes:
            # Monte tout le code source de l'application dans le conteneur
            -
                type: bind
                source: ${LOCAL_SITE_ROOT}
                target: ${DOCKER_SITE_ROOT}

